server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellonayeon/spring-cloud-config.git
#          # private repository
#          username: [your username]
#          password: [your password]
