server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/code/native-file-repo
        git:
          uri: https://github.com/hellonayeon/spring-cloud-config.git
#          # private repository
#          username: [your username]
#          password: [your password]
