server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/code/native-file-repo
        git:
          uri: https://github.com/hellonayeon/spring-cloud-config.git
#          # private repository
#          username: [your username]
#          password: [your password]
management:
  endpoints:
    web:
      exposure:
        include: health, busresfresh, beans, refresh
